name: Deploy test branch

on:
  push:
    paths-ignore:
      - '*.md'
      - '.github/docs/**'
      - 'CODEOWNERS'
    branches:
      - test

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}